---

- name: Add harbor2 helm chart repo
  kubernetes.core.helm_repository:
    # binary_path: /opt/bin/helm
    name: harbor
    repo_url: "https://helm.goharbor.io"

- name: Install Helm Diff
  kubernetes.core.helm_plugin:
    plugin_path: "https://github.com/databus23/helm-diff"
    state: present
